### ISSUE TITLE
@grpc/proto-loader and readFileSync fails to load files in Vercel/Netlify

### ISSUE THREAD

**Issue by Richard87** [vercel/nft#245]
Hi!

I'm struggling with including files in my api functions. Specifically I want to include proto files, but everything is failing now...

All code works flawless when running `next dev`, but failing on Vercel ~~and on Netlify~~, also when running `netlify dev`

All code is here: https://github.com/richard87/protoloader

I have created a simple reproduction of the error, and deployed it at Vercel and Netlify to test:
https://protoloader.vercel.app/api/json / https://protoloader.vercel.app/api/grpc
https://protoloader-test.netlify.app/api/json / https://protoloader-test.netlify.app/api/grpc

This is my grpc.js api function:
```js
const protoLoader = require('@grpc/proto-loader');

const grpcOptions = {
  keepCase: true,
  longs: String,
  enums: String,
  defaults: true,
  oneofs: true
};

const protoFile = "test.proto";

export const config = {
  unstable_includeFiles: ['test.proto'],
};

export default function handler(req, res) {
  const packageDefinition = protoLoader.loadSync( protoFile, grpcOptions);
  res.status(200).json(packageDefinition)
}
```

And my vercel.json file:
```
{
  "functions": {
    "api/json.js": {
      "includeFiles": "test.json"
    },
    "api/grpc.js": {
      "includeFiles": "test.proto"
    }
  }
}
```

With the error log:
```
Vercel:
2021-11-07T19:43:37.835Z	dd740350-1ac3-43c1-819b-cfcfe848babc	ERROR
	Error: ENOENT: no such file or directory, open 'test.proto' 
   at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at fetch (/var/task/node_modules/protobufjs/src/root.js:172:34) 
   at Root.load (/var/task/node_modules/protobufjs/src/root.js:206:13) 
   at Root.loadSync (/var/task/node_modules/protobufjs/src/root.js:247:17)
    at Object.loadProtosWithOptionsSync (/var/task/node_modules/@grpc/proto-loader/build/src/util.js:66:29)
    at Object.loadSync (/var/task/node_modules/@grpc/proto-loader/build/src/index.js:194:31)
    at handler (/var/task/.next/server/pages/api/grpc.js:38:43)
    at Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:102:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

 {  errno: -2,  syscall: 'open',  code: 'ENOENT',  path: 'test.proto'}

Netlify:
{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "Error: ENOENT: no such file or directory, open 'test.proto'",
  "trace": [
    "Runtime.UnhandledPromiseRejection: Error: ENOENT: no such file or directory, open 'test.proto'",
    "    at process.<anonymous> (/var/runtime/index.js:35:15)",
    "    at process.emit (events.js:314:20)",
    "    at processPromiseRejections (internal/process/promises.js:209:33)",
    "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
  ]
}
```

I have looked at clues for a solution in 
https://github.com/vercel/nft/issues/194
https://github.com/vercel/next.js/issues/8251

Extra:
Adding this netlify.toml solved the issue on Netlify, but the problem still persists on Vercel
```toml
[functions]
  # Includes all Markdown files inside the "files/" directory.
  included_files = ["test.json", "test.proto"]
```

**Comment by styfle** [comment]
I think that `unstable_includeFiles` isn't used for Next.js APIs yet, only Pages. cc @ijjk 

The easiest way to get `nft` to include a file is to read it like this:

```js
import { readFileSync } from 'fs'
import { join } from 'path'

const file = readFileSync(join(process.cwd(), 'test.proto'));
```

**Comment by styfle** [comment]
This will fix it https://github.com/Richard87/protoloader/pull/1
